# This is a basic workflow to help you get started with Actions

name: Check Shell Scripts

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    paths:
      - "**.sh"
      - ".github/workflows/check_shell.yml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.1.7
        
      - name: Check Shell Scripts
        uses: Klintrup/simple-shell-syntax-check@v2.2.0

