# This is a basic workflow to help you get started with Actions

name: Patch image with Magisk

# Controls when the workflow will run
on:
  push:
    paths:
      - '.github/workflows/magisk_root.yml'
      - 'util_functions.sh'
  workflow_dispatch:
  workflow_run:
    workflows: ['Compile Kernel from Source']
    types: 
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4.1.7

      - name: Download kernel images
        uses: dawidd6/action-download-artifact@v6  
        with:
          workflow: compile_from_source.yml

      - name: Download Magisk v27.0
        run: |
          ls
          mkdir Magisk
          cd Magisk
          curl -L https://github.com/topjohnwu/Magisk/releases/download/v27.0/Magisk-v27.0.apk > Magisk.apk
          unzip Magisk.apk

      - name: Fetch relevant files from Magisk
        run: |
          mkdir Magic
          cp Magisk/assets/boot_patch.sh Magic
          cp Magisk/lib/x86_64/libmagiskboot.so Magic
          cp Magisk/lib/armeabi-v7a/libmagisk32.so Magic
          cp Magisk/lib/arm64-v8a/libmagisk64.so Magic
          cp Magisk/lib/arm64-v8a/libmagiskinit.so Magic

      - name: Fetch other files needed 
        run: |
          cp util_functions.sh Magic
          cp the-images/boot.img Magic

      - name: Run the magic
        run: |
          chmod +x Magic/*
          cd Magic
          sh boot_patch.sh boot.img
  
