# This is a basic workflow to help you get started with Actions

name: Patch image with Magisk

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ['Compile Kernel from Source']
    types: 
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:

      - name: Download kernel images
        uses: actions/download-artifact@v4.1.7
        with:
          name: 'Compile Kernel from Source'

      - name: Download Magisk repo
        run: |
          git clone https://github.com/topjohnwu/Magisk

      - name: Unzip folder
        run: |
          unzip the-images.zip

      - name: Run magisk script
        if: false
        run: |
          chmod +x boot_patch.sh
          sh boot_patch.sh to-upload/boot.img
  
