# This is a basic workflow to help you get started with Actions

name: Compile Kernel

# Controls when the workflow will run
on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Update packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade

      - name: Install Repo
        run: |
          sudo apt-get install repo

      # Runs a set of commands using the runners shell
      - name: Sync kernel repo
        run: |
          mkdir android-kernel
          cd android-kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b android14-gs-pixel-6.1
          repo sync -c --no-tags

      - name: Download Factory Images (Update vendor ramdisk)
        run: |
          cd ..
          curl -o "https://dl.google.com/dl/android/aosp/raven-ap1a.240505.004-factory-9d783215.zip"

      - name: Update vendor ramdisk
        run: |
          unzip raven-ap1a.240505.004-factory-9d783215.zip
          cd raven-ap1a.240505.004
          unzip image-raven-ap2a.240505.004.zip vendor_boot.img
          mv vendor_boot.img ..
          android-kernel/tools/mkbootimg/unpack_bootimg.py --boot_img vendor_boot.img \ --out vendor_boot_out
          curl "https://dl.google.com/dl/android/aosp/raven-ap1a.240505.004-factory-9d783215.zip" -O
          ls
