# This is a basic workflow to help you get started with Actions

name: Compile Kernel

# Controls when the workflow will run
on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Update packages
        run: |
          sudo apt-get update
          sudo apt-get upgrade

      - name: Install Repo
        run: |
          sudo apt-get install repo

      # Runs a set of commands using the runners shell
      - name: Sync kernel repo
        run: |
          mkdir android-kernel
          cd android-kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b android14-gs-pixel-6.1
          repo sync -c --no-tags

