# This is a basic workflow to help you get started with Actions

name: Update Kernel Source Code

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo 
        uses: actions/checkout@v4.1.7
        with:
          ref: kernel-source

      - name: Delete old android-kernel (if it exists)
        run: |
          ls
          rm -rf android-kernel/
    
      - name: Download packages needed
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install repo

      - name: Free up space
        uses: jlumbroso/free-disk-space@main

      # Runs a single command using the runners shell
      - name: Sync kernel source
        run: |
          mkdir android-kernel
          cd android-kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b android14-gs-pixel-6.1
          repo sync -c --no-tags

      - name: Upload entire kernel source
        run: |
          git add android-kernel
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Updated kernel source code" 
          git push origin kernel-source
